/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathGenerator;

import java.awt.*;

import mathGenerator.problems.Problem;

/**
 *
 * @author Students
 */
public class ProblemDisplay extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form ProblemDisplay
	 */
	public ProblemDisplay() {
		initComponents();
	}

	public ProblemDisplay(Problem problem, char operator) {
		String first;
		String second;
		if (problem.getFirst() % 1 == 0) {
			first = Integer.toString((int) problem.getFirst());
		} else {
			first = Double.toString(problem.getFirst());
		}
		if (problem.getSecond() % 1 == 0) {
			second = Integer.toString((int) problem.getSecond());
		} else {
			second = Double.toString(problem.getSecond());
		}
		this.problem = problem;

		initComponents();
		setLayout(null);
                
                switch(operator)
                {
                    case '*':
                        operator='Ã';
                        break;
                    case '/':
                        operator='Ã';
                        break;
                    case '+':
                    case '-':
                    default:
                        break;
                }
                
		label.setText(first + " " + operator + " " + second + " " + "= ?");
		label.setLocation(5, 5);
		label.setSize(label.getPreferredSize());
		text.setSize(new Dimension(80, 30));
		text.setLocation(0, 20);
		super.setSize(90, 48);
		revalidate();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		label = new javax.swing.JLabel();
		text = new javax.swing.JFormattedTextField();

		label.setText("an equation");
		label.setMaximumSize(new java.awt.Dimension(80, 14));
		label.setMinimumSize(new java.awt.Dimension(80, 14));
		label.setPreferredSize(new java.awt.Dimension(80, 14));

		text.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				textFocusLost(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														label,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(text))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(label,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										16,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(text,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										20,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>//GEN-END:initComponents

	private void textFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_textFocusLost
		problem.answer(text.getText());
		answer = text.getText();
	}// GEN-LAST:event_textFocusLost

	public String getAnswer() {
		return answer;
	}

	public void clearAnswer() {
		answer = "";
		text.setText("");
	}

	public void disableAnswer() {
		text.setEnabled(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel label;
	private javax.swing.JFormattedTextField text;
	// End of variables declaration//GEN-END:variables
	protected String answer;
	protected Problem problem;
}
