/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathGenerator;

import java.awt.*;

import mathGenerator.problems.Problem;

/**
 *
 * @author Students
 */
public class RemainderProblemDisplay extends ProblemDisplay {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form ProblemDisplay
	 */
	public RemainderProblemDisplay() {
		initComponents();
	}

	public RemainderProblemDisplay(Problem problem, char operator) {
		String first;
		String second;
		if (problem.getFirst() % 1 == 0) {
			first = Integer.toString((int) problem.getFirst());
		} else {
			first = Double.toString(problem.getFirst());
		}
		if (problem.getSecond() % 1 == 0) {
			second = Integer.toString((int) problem.getSecond());
		} else {
			second = Double.toString(problem.getSecond());
		}
		this.problem = problem;

		initComponents();
		setLayout(null);
		label.setText(first + " " + operator + " " + second + " " + "= ?");
		label.setLocation(5, 5);
		jLabel1.setLocation(42, 24);
		jLabel1.setSize(9, 20);
		label.setSize(label.getPreferredSize());
		text.setSize(new Dimension(39, 30));
		text.setLocation(0, 20);
		text1.setSize(new Dimension(29, 30));
		text1.setLocation(50, 20);
		super.setSize(90, 48);
		revalidate();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		label = new javax.swing.JLabel();
		text = new javax.swing.JFormattedTextField();
		text1 = new javax.swing.JFormattedTextField();
		jLabel1 = new javax.swing.JLabel();

		label.setText("an equation");
		label.setMaximumSize(new java.awt.Dimension(80, 14));
		label.setMinimumSize(new java.awt.Dimension(80, 14));
		label.setPreferredSize(new java.awt.Dimension(80, 14));

		text.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				textFocusLost(evt);
			}
		});

		text1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				text1FocusLost(evt);
			}
		});

		jLabel1.setText("r");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		label,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		text,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		39,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		text1)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(label,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										16,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														text,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														20,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														text1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														20,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))));
	}// </editor-fold>//GEN-END:initComponents

	private void textFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_textFocusLost
		problem.answer(text.getText());
		answer = text.getText();
	}// GEN-LAST:event_textFocusLost

	private void text1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_text1FocusLost
		((mathGenerator.problems.DivisionProblem) problem).answerRem(text1
				.getText());
		remainder = text1.getText();
	}// GEN-LAST:event_text1FocusLost

	public String getRemainder() {
		return remainder;
	}

	public void clearAnswer() {
		answer = "";
		remainder = "";
		text.setText("");
		text1.setText("");
	}

	public void disableAnswer() {
		text.setEnabled(false);
		text1.setEnabled(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel label;
	private javax.swing.JFormattedTextField text;
	private javax.swing.JFormattedTextField text1;
	// End of variables declaration//GEN-END:variables
	protected String remainder;
}
